modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/ItsThosea/BadOptimizations/issues"
# Forge 1.20.4- requires mod icon to be in root folder
logoFile="badoptimizations-icon.png"
logoBlur=false

[[mods]]
   modId="badoptimizations"
   version="${version}"
   displayName="BadOptimizations"
   authors="Thosea"
   description='''
   Optimization mod that focuses on things other than rendering
   '''
[[dependencies.badoptimizations]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.21.2,)"
   ordering="NONE"
   side="CLIENT"

[[mixins]]
config = "badoptimizations.mixins.json"